const Angle = require('./Angle.png');
const arrowRight = require('./arrowRight.png');
const arrowTop = require('./arrowTop.png');
const battery = require('./battery.png');
const batteryStatus = require('./batteryStatus.png');
const btnBg = require('./btnBg.png');
const btnBgDis = require('./btnBgDis.png');
const checkBox = require('./checkBox.png');
const checkBoxed = require('./checkBoxed.png');
const childLock = require('./childLock.png');
const deleteIcon = require('./deleteIcon.png');
const dryAgent = require('./dryAgent.png');
const dryProduct = require('./dryProduct.png');
const edit = require('./edit.png');
const empty = require('./empty.png');
const feed = require('./feed.png');
const feedDis = require('./feedDis.png');
const inform = require('./inform.png');
const instrution = require('./instrution.png');
const light = require('./light.png');
const plan = require('./plan.png');
const powerType = require('./powerType.png');
const productLogo = require('./productLogo.png');
const record = require('./record.png');
const reset = require('./reset.png');
const setting = require('./setting.png');
const tabBg = require('./tabBg.png');
const voice = require('./voice.png');
const warn = require('./warn.png');
const workCat = require('./workCat.png');
const workFail = require('./workFail.png');
const workPlan = require('./workPlan.png');
const workSuccess = require('./workSuccess.png');

const Res = { Angle, arrowRight, arrowTop, battery, batteryStatus, btnBg, btnBgDis, checkBox, checkBoxed, childLock, deleteIcon, dryAgent, dryProduct, edit, empty, feed, feedDis, inform, instrution, light, plan, powerType, productLogo, record, reset, setting, tabBg, voice, warn, workCat, workFail, workPlan, workSuccess };

export default Res;